/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'wangqiang' at '16-1-29 下午5:50' with Gradle 2.10
 *
 * @author wangqiang, @date 16-1-29 下午5:50
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
